pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'whoami'
        sh 'cd spring-boot-app && mvn clean package'
        sh 'echo Hello'
        sh 'pwd'

      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://99.79.38.23:9000"
        SONAR_TOKEN = "sqa_784b4e777ae485c55e73dc3a6a61a83552dfd1d0" 
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube-token	', variable: 'SONAR_AUTH_TOKEN')]) {
          //sh 'cd spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
          sh 'cd spring-boot-app && mvn sonar:sonar -Dsonar.login=sqa_784b4e777ae485c55e73dc3a6a61a83552dfd1d0 -Dsonar.host.url=http://99.79.38.23:9000'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "esraaelhasanen/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('dockerhub-pass')
      }
      steps {
        script {
            sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "dockerhub-pass") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "spring-boot-welcome-app"
            GIT_USER_NAME = "esraaelhasanen66-soror"
        }
        steps {
            withCredentials([string(credentialsId: 'github-pat', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "esraa.elhasanen66@gmail.com"
                    git config user.name "esraaelhasanen66-soror"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
                    git add spring-boot-app-manifests/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
    }
  }
}